[package]
name = "godot_egui"
description = "Egui backend for the Godot Engine"
homepage = "https://github.com/setzer22/godot-egui"
repository = "https://github.com/setzer22/godot-egui"
license = "MIT"
version = "0.1.7"
authors = ["Setzer22"]
keywords = ["gamedev", "gui"]
edition = "2018"
readme = "../README.md"
workspace = ".."

[dependencies]
gdnative = "0.9.3"
egui = "0.14.2"
egui_stylist = { version = "0.1.3", git = "https://github.com/jacobsky/egui-stylist"  }
ron = "0.6.4"

